version: "3.4"
volumes:
  dbstorage: ~
  public:
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - public:/app/public
  database:
    image: mysql:8.0
    volumes:
      - dbstorage:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    ports:
      - 13306:3306
  nginx:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - public:/app/public
