version: "3.4"
volumes:
  dbstorage: ~
  public:
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - public:/app/public
  database:
    image: mysql:8.0
    volumes:
      - dbstorage:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    ports:
      - 13306:3306
  nginx:
    image: nginx:alpine
    restart: always
    labels:
      - "traefik.enable=true"
      - 'traefik.frontend.rule=Host:hulahop.h91.co'
      - "traefik.port=80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - public:/app/public
  proxy:
    image: traefik:1.7.21
    command: --web -c /etc/traefik/traefik.toml --LOGLEVEL=debug
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - /acme



