version: "3.4"
volumes:
  dbstorage: ~
services:
  php:
    build: .
    volumes:
      - ./:/hula-hop
  database:
    image: mysql:8.0
    volumes:
      - dbstorage:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    ports:
      - 13306:3306
  nginx:
    image: nginx:1.17
    ports:
      - 18081:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/hula-hop/public